### ISSUE TITLE
Internally defined strings cannot be translated

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/arg_router#214]
These publicly exposed internally defined string types have no mechanism to override them for multi-lang support:
* `alias_group` and `one_of` add text to their help output
* Exception messages
* The above but for any user-defined or 3rd party nodes/policies

## Tasks
- [x] Add a new string type `error_name_t` which will be used by node implementers to override the node's representation in error output (i.e. the string returned by `parsing::node_token_type<>()`)
- [x] Allow the user to specify a `display_name_t` for `alias_group` and `one_of`; if not present use the existing internal string.  Modify `detail::generate_string_of_child_names` to use the display name as the prefix, which ultimately sets the internal `error_name_t` policy.  Change the help for both node types to use the display name
- [x] Create an error enum that contains representations of all the error messages in the codebase
- [x] Create a new exception with similar constructors to `parse_exception` that accepts the error code enum underlying type (so it can be extended by others) instead of a string message.  It will also need to carry a `vector<parsing::token_type>`.  Replace all uses of `parse_exception` in the codebase and tests, with the new type.  Tests that test for the exception message/type will need updating, but root-level tests will continue to fail
- [x] Add a new policy that attaches to the root that sets the current `multi_lang::translation` specialisation.  If one is not defined, then use an internal `err_en_GB` one that just carries the error messages
- [x] Wrap the `root::parse(..)` and `help(..)`  methods so that thrown _new type_ exceptions are caught.  Their error code is mapped to the corresponding string via the previously defined policy, and then they are re-thrown as a `parse_exception` using the mapped string.  Root-level tests should now pass
- [x] Add validator rule so that only the root can have a `policy::exception_translator`
- [x] Update `multi_lang` and `root` tests for the mapping
- [x] Update the `simple_ml` examples to incorporate the error message translations
- [x] Update README.md for the same reason
- [x] Update related pages for `multi_lang_exception`
