### ISSUE TITLE
Create `help`

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/arg_router#24]
### Requirements:
- A new policy which tree nodes can use to hide themselves from the help node
- Help node is arg-like, so should be named and appear in it's own output
- A routing phase is optional.  If present the arg is a single `std::string` of the formatted output, otherwise the output is printed to the console and `exit(EXIT_SUCCESS)` is called
- Needs to be accessible from the root so help can be printed from user code
- Should support user specified program name, version and intro blurb; and if present, they will be used in the help output
- Help needs to support full 'flat' output, but it also needs to support a per-mode output e.g. `food --help parent_mode child_mode`.  By default it will do per node output, but flat output can be forced with a policy

### Implementation Thoughts
Help nodes should expose a method that can be detected by the root, this way we can access help from the root but we retain the ability to replace the help policy.  Accessing help from the root when there is no help policy is a compile-time failure.  This help node method should return the formatted string, *not* call the same built-in or custom routing that a parse call would.

Three new CTS policies should be made for the help mode: `program_name`, `program_version`, `program_intro`,  and `flatten_help`.  They do exactly what you think they would.

The core of the help type system is an alias that all nodes that wish to display help will publicly expose:
```
template <bool Flatten>
struct help_data_type {
    using label = S_("...");                   // e.g. "--help,-h" or "Mode 1".  Can be empty as long as there are children
    using description = S_("...");             // Generally the policy::description_t output, but can be empty
    using children = std::conditional<         // May be empty.  Flatten can be ignored
        Flatten,
        std::tuple<
            typename child1::help_data_type,
            ...
        >,
        std::tuple<>
    >;
};
```
A default implementation in `tree_node` will be provided that is suitable for all leaf node types, called `default_help_data_type`.  The string generation in `help` will space the label and description fields appropriately.  It will also create the 'piping' and indentation e.g.:
```
--help           Display the help output
--version, -v    Display the program version
  ┌ --apple, -a
  ├ -b
  └ --coffee, -c
```
Here the last three flags are the anonymous mode, which has an empty label and description but all the children.  A tree node with no public `help_data_type` will be ignored by the help node.

Unless the `flatten_help` policy is present, it accepts arguments.  These are the names of nodes in descendent order, the last one being the one you wish to display help for.  `help` will recurse through the children and then build the string output from that parent.

When `help` queries the parse tree's `help_data_type`s when `flatten_help` is present, it will pass `true` as the `Flatten` template parameter.  The help node will generate the string data as normal, it will just be bigger.

It's tempting at this stage to offer the ability to use a formatting policy, or colour output, etc.  But let's get the bare minimum working first.

### Tasks
- [x] Create the new policies
- [x] Help node framework and formatted string generation
- [x] Built-in or custom routing support
- [x] Expose help in the `root_t` public API
- [x] Validator updates
- [x] Unit tests
- [x] Test that string defines work in the `S_()` macro, as that will be a common program name and version pattern
- [x] Update ReadMe.md
