### ISSUE TITLE
Add support for multi-value arguments

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/arg_router#314]
Currently `arg_t` is fixed at a single value, however the library needs a multiple length one as currently the variable length value token supporting node is `positional_arg_t` which obviously cannot be named.

We need to create a new `multi_arg_t` type that supports this feature, and then implementing `arg_t` on top of it should be simple.  It is also required that the node allows support for `none_name_t` naming this is to support the 'forwarding marker' pattern which is a common enough feature of programs that launch others, where they have their own command line parsing first, then a special identifier (typically `--`) which indicates that the following tokens should be forwarded as is to the program(s) being launched.  This is an extension of #321.

The new type must support an arbitrary amount of string arguments (including zero), either by a default unbounded state (like `positional_arg_t`) or by the user specifying their own `min_max_count_t` policy.

### Tasks
- [x] Allow easy inheritability of nodes
- [x] Implement `multi_arg_t`, unit tests, death tests, and root tests
- [x] Add new validator rule for `multi_arg_t` for the usual rules
- [x] Implement `forwarding_arg_t`, unit tests, death tests, and root tests
- [x] Add new validator rule for `forwarding_arg_t` for the usual rules
- [x] Simplify the `custom_policy_and_node` example
- [x] Update docs
