### ISSUE TITLE
Review parsing code

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/arg_router#320]
The pre-parsing code, specifically in policies, could do with another look over.  #314 caught some oddities that were unnecessarily complicating the code base  - I have no doubt that there is more.

Also during #314 I discovered that moving the `parse_target` validation check to the top of the pre-parsing code in `tree_node` broke many tests but I couldn't see why, so this needs explicitly investigating.

This should also lead to better documentation as currently it is very lacking.

### Tasks
- [x] Review existing parsing code in all policies and node types
- [x] Investigate the `parse_target` issue noted above.  It either has a very good reason why it doesn't work that needs documenting, or it needs fixing
- [x] Update the parsing architectural documentation.  Images would be very helpful as the wording can get very complicated

### Investigation Result
The tests are failing because `mode` relies on the child `pre_parse(..)` method returning before the `pre_parse_data::validator(..)` method if there's no label token match - it uses this data to throw an `argument_has_already_been_set`.

However, I'm inclined to think that this is all correct.  The parent node should only be requested for validation if this node is the target one, and in order to do that the tokens need running through the full pre-parse sequence.
