### ISSUE TITLE
Add variable list length end token

### ISSUE THREAD

**Issue by cmannett85** [cmannett85/arg_router#321]
This was originally a part of #314 but has now been split into its own ticket.

Currently there can only be one node with variable length value tokens (e.g. `positional_arg_t`), and it must be at the end.  However we can 'chain' together multiple nodes of this type if we could define a token that marks the end of the list.  A potential real-world pattern for this is token forwarding to launched child process:
```
$ launcher prog1 prog2 prog3 -- arg1 arg2 arg3
```
In the above example the programs to launch are in the first variable length list using `--` to mark the end of it, and the arguments following the second.

We would also need to create a new policy that acts as the end-marker, in the case shown above it would be --. This marks the end of the node's tokens at runtime, but it is still considered non-fixed-count at compile-time (and therefore by the validator).
```
mode(
    positional_arg<std::vector<int>>("foo"_S,
        policy::token_end_marker{"--"_S}),
    positional_arg<std::vector<std::string_view>>("bar"_S),
    policy::router([](bool, std::vector<std::string_view>) { .. })
```
### Tasks
- [x] Update validator's `positional_args_must_have_fixed_count_if_not_at_end` to not be dependent on `positional_arg_t`.  It should check that non-fixed-count and non-multi-stage-values are at the end.  Rename appropriately and update tests
- [x] Implement `token_end_marker` policy, unit tests, death tests.   Add `has_*` trait that looks for `token_end_marker` method
- [x] Prevent `token_end_marker` on non-variable length value list nodes
- [x] Update validator's `positional_args_must_have_fixed_count_if_not_at_end` (or whatever its new name is) so that it ignores nodes with a `token_end_marker` policy.  Update tests
- [x] Update `min_max_count_t` to detect `token_end_marker`
- [x] Add root tests for `token_end_marker`
- [x] Update docs and add new example, including updating the translated exception one for the new EC
